# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lilinux/Téléchargements/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/lilinux/Téléchargements/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lilinux/Documents/5TC/RobotCleaner2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lilinux/Documents/5TC/RobotCleaner2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/lilinux/Téléchargements/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/lilinux/Téléchargements/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lilinux/Documents/5TC/RobotCleaner2/CMakeFiles /home/lilinux/Documents/5TC/RobotCleaner2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lilinux/Documents/5TC/RobotCleaner2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named robot_cleaner2

# Build rule for target.
robot_cleaner2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 robot_cleaner2
.PHONY : robot_cleaner2

# fast build rule for target.
robot_cleaner2/fast:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/build
.PHONY : robot_cleaner2/fast

src/action.o: src/action.cpp.o

.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i

.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s

.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/dp.o: src/dp.cpp.o

.PHONY : src/dp.o

# target to build an object file
src/dp.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/dp.cpp.o
.PHONY : src/dp.cpp.o

src/dp.i: src/dp.cpp.i

.PHONY : src/dp.i

# target to preprocess a source file
src/dp.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/dp.cpp.i
.PHONY : src/dp.cpp.i

src/dp.s: src/dp.cpp.s

.PHONY : src/dp.s

# target to generate assembly for a file
src/dp.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/dp.cpp.s
.PHONY : src/dp.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/montecarlo.o: src/montecarlo.cpp.o

.PHONY : src/montecarlo.o

# target to build an object file
src/montecarlo.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/montecarlo.cpp.o
.PHONY : src/montecarlo.cpp.o

src/montecarlo.i: src/montecarlo.cpp.i

.PHONY : src/montecarlo.i

# target to preprocess a source file
src/montecarlo.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/montecarlo.cpp.i
.PHONY : src/montecarlo.cpp.i

src/montecarlo.s: src/montecarlo.cpp.s

.PHONY : src/montecarlo.s

# target to generate assembly for a file
src/montecarlo.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/montecarlo.cpp.s
.PHONY : src/montecarlo.cpp.s

src/qlearning.o: src/qlearning.cpp.o

.PHONY : src/qlearning.o

# target to build an object file
src/qlearning.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearning.cpp.o
.PHONY : src/qlearning.cpp.o

src/qlearning.i: src/qlearning.cpp.i

.PHONY : src/qlearning.i

# target to preprocess a source file
src/qlearning.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearning.cpp.i
.PHONY : src/qlearning.cpp.i

src/qlearning.s: src/qlearning.cpp.s

.PHONY : src/qlearning.s

# target to generate assembly for a file
src/qlearning.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearning.cpp.s
.PHONY : src/qlearning.cpp.s

src/qlearningLinearApprox.o: src/qlearningLinearApprox.cpp.o

.PHONY : src/qlearningLinearApprox.o

# target to build an object file
src/qlearningLinearApprox.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearningLinearApprox.cpp.o
.PHONY : src/qlearningLinearApprox.cpp.o

src/qlearningLinearApprox.i: src/qlearningLinearApprox.cpp.i

.PHONY : src/qlearningLinearApprox.i

# target to preprocess a source file
src/qlearningLinearApprox.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearningLinearApprox.cpp.i
.PHONY : src/qlearningLinearApprox.cpp.i

src/qlearningLinearApprox.s: src/qlearningLinearApprox.cpp.s

.PHONY : src/qlearningLinearApprox.s

# target to generate assembly for a file
src/qlearningLinearApprox.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/qlearningLinearApprox.cpp.s
.PHONY : src/qlearningLinearApprox.cpp.s

src/state.o: src/state.cpp.o

.PHONY : src/state.o

# target to build an object file
src/state.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/state.cpp.o
.PHONY : src/state.cpp.o

src/state.i: src/state.cpp.i

.PHONY : src/state.i

# target to preprocess a source file
src/state.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/state.cpp.i
.PHONY : src/state.cpp.i

src/state.s: src/state.cpp.s

.PHONY : src/state.s

# target to generate assembly for a file
src/state.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/state.cpp.s
.PHONY : src/state.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/robot_cleaner2.dir/build.make CMakeFiles/robot_cleaner2.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... robot_cleaner2"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/dp.o"
	@echo "... src/dp.i"
	@echo "... src/dp.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/montecarlo.o"
	@echo "... src/montecarlo.i"
	@echo "... src/montecarlo.s"
	@echo "... src/qlearning.o"
	@echo "... src/qlearning.i"
	@echo "... src/qlearning.s"
	@echo "... src/qlearningLinearApprox.o"
	@echo "... src/qlearningLinearApprox.i"
	@echo "... src/qlearningLinearApprox.s"
	@echo "... src/state.o"
	@echo "... src/state.i"
	@echo "... src/state.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

